version: '3.4'
services:
  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: super-secret
      MYSQL_DATABASE: euregio-bigband
  web:
    build: .
    image: euregio-bigband
    ports:
      - "4200:80"
    links:
      - mariadb
    command: bin/setup
    volumes:
      - './public/index.php:/app/public/index.php'
      - './public/wp-config.php:/app/public/wp-config.php'
      - './config:/app/config'
      - './bin:/app/bin'
      - './composer.json:/app/composer.json'
      - './composer.lock:/app/composer.lock'
    cap_add:
      - SYS_TIME
      - SYS_NICE
    environment:
      APACHE_SERVER_NAME: euregio-bigband.local
      DATABASE_URL: mariadb://root:super-secret@mariadb:3306/euregio-bigband
      AUTH_KEY: '#u]UKwb&aZw8p5_KX^LFrX9Q5,0;a6t0<uG. -:Rl.weW8`m&f-?vLi--yI8,_*'
      SECURE_AUTH_KEY: '@Gb?p%vLNjUS>VOgQb+#Fk}]24sp@;z}Hml`lrK>XeE <.wrcaf=+TuFtr.Fw#4'
      LOGGED_IN_KEY: '4#8ms*,Qd7a 7!uNM(zQmg|,aP&+-ydAV;YkJ)kv24S/p|sBb,qO.*TQOl]*+{#z'
      NONCE_KEY: 'V_yQ>9/,>?/?t#G~mPxcHK#Q!U2e1zcb`5#iy6IbbCUzuV4^W60W2uV<<D T;{L'
      AUTH_SALT: '93LLO*SA@%@@4ztp[PEh713Ti:6PbGZ*,(~unq {w;zT.PH &5qBC,66-Ag44XSK'
      SECURE_AUTH_SALT: '#[PA-fhd1.>9N7ld|Xlh@kkP)@F?jX82V!=SVDa-U@Wr~MW=83.du1`rZ.aSiOj'
      LOGGED_IN_SALT: 's_;G}iS383?M^c513scR&seL/ p<z++ps+().HV=[C&C.&/>Fh0)YMTy%FF%>N!'
      NONCE_SALT: 'mpgL4) HqnVrVefpb!+D.7E^;g?3kYG+][[vd]ZAh<jw4)CleJun@A8VY-7S]2?'
      HOME_URL: http://localhost:4200
      SITE_URL:  http://localhost:4200
      SITE_TITLE: Euregio Bigband
      ADMIN_USER: euregio
      ADMIN_EMAIL: euregio@example.com
      ADMIN_PASSWORD: super-secret
      WP_CLI_CACHE_DIR: /tmp/wp-cli




